# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: .NET Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/RAS.sln
    
    - name: Build
      run: dotnet build ./src/RAS.sln --no-restore
    
    - name: Build
      run: dotnet test ./src/RAS.sln --no-build --verbosity normal
